[build]
  command = "astro build"
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/edge/*"
  to = "/.netlify/edge-functions/:splat"
  status = 200