on:
  push:
    branches: [main]

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup pnpm
        uses: pnpm/setup@v3
        with:
          require-lockfile: true

      - name: Build static website
        run: pnpm build

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.16.3"
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform -chdir=infra init -input=false

      - name: Terraform Format
        run: terraform -chdir=infra fmt -check

      - name: Terraform Apply
        run: terraform -chdir=infra apply -auto-approve -input=false
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          TF_VAR_account_id: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          TF_VAR_zone_id: ${{ vars.CLOUDFLARE_ZONE_ID }}
          TF_VAR_domain: ${{ vars.DOMAIN }}
